site_name: SwiftWing 产品介绍 文档

site_description: SwiftWing 产品介绍 文档
site_author: SwiftWing 团队
site_url: https://swiftwing001.github.io/SwiftWing-Product-Introduction/

theme:
  name: readthedocs

nav:
  - 主页: index.md
  - 产品介绍:
    - P1无人机分电板: 0_P1无人机分电板.md
    - 迅翼MS4525DO空速计: 1_迅翼MS4525DO空速计.md


# # 本地编译
# mkdocs build
# # 本地预览确认
# mkdocs serve
# # 提交源码到 main 分支
# git add .
# git commit -m "更新内容"
# git push origin master
# # 部署到 GitHub Pages
# mkdocs gh-deploy